language: r
cache: packages

before_install:
  - tlmgr install standalone

addons:
  apt:
    packages:
      - libmagick++-dev

after_success:
- Rscript -e 'devtools::install(); library(texPreview);sapply(c("standalone",texPreview:::tex_pkgs),texPreview:::check_package);tex_opts$set(returnType="tex",cleanup="aux");texPreview(obj = xtable::xtable(head(iris,10)));cat(readLines(list.files(tempdir(),pattern = "log",full.names = TRUE)));'
