language: r
cache: packages

before_install:
  - tlmgr install standalone

addons:
  apt:
    packages:
      - libmagick++-dev

after_success:
- Rscript -e 'devtools::install(); texPreview::texPreview(obj = xtable::xtable(head(iris,10)));'
