language: r
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo

r_github_packages:
- yonicd/covrpage
- metrumresearchgroup/pkgdown

after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
after_failure:
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_KEY"
  keep-history: true
  local-dir: docs
  on:
    branch: check_tex_pkgs
env:
  global:
    secure: DInRi1w6EtiEr85i0etsXqQSdJwNVlzyWLYFQfLJVDta1WWziXvSUeC8BrpKGLnfhnO4K5d46xAgxACt2yhUm2LXJF8oWG9GSyMdBiLF9kZa+EV2HlmE6asAfo2vJela7gySCMcrd8hKaghnQkIp51lbDEveFG4SjPZWJiVXwne4PQ8Vv1Hb4S59SX+FXFzNHMSNcHlvIyw+0bd9B3nW4uHYYKRNY+O3WetnLkhsRckO/MBFQmutKy6quOYDSihmtSShLttvuXI/wOro2RRgzQkMm17ynGtHQV5C9vzph6DPRHuniYga6FMGLucgiiTDytfppCI+0/KRAvS0IZG6mP6JsjtXp8tK74ZD2IXUrim5pR3qfTdox2yjzAKhvU5WxcDIyRS9AIN3ntqye0wOtEMi9/qB5ba8EoxcTuTFqMjjspJO7rJBSvyOUT0BabE8BQzzzzc8gLm1M6HrQF3/xwdbEKmZ1hSYRXU98ZwF/cyb+sH7UZ32bHIaOPZXk2ql6HvOg3ifAsBfLvo39NL9xPD7slkd8J+PIzczpuCKLufk8sshp3nvNmsSDC7NUHJPzpV0+bWpnBhh0Ig857Negh4VS6hs+wqnNy5Keelid8o1KXp9bRin08x9KFutt/Z5k+DAblup9ofLgPJgPdE0xWVIp3dBGAnUuowTEouKlaY=
