language: r
cache: packages
addons:
  apt:
    packages:
    - libmagick++-dev
after_success:
- Rscript -e 'devtools::install(); tex_opts$set(returnType = "tex");texPreview::texPreview(obj = xtable::xtable(head(iris,10)));'
