language: r
cache: packages
addons:
  apt:
    packages:
    - libmagick++-dev
    - texlive-latex-extra
after_success:
- Rscript -e 'devtools::install(); library(texPreview); tex_opts$set(returnType = "tex"); texPreview::texPreview(obj = xtable::xtable(head(iris,10)));'
